### ISSUE TITLE
Crunchyroll is not working

### ISSUE THREAD

**Issue by JairHuamanBellido** [Ridaniel/Fibonacci#1]
Steps:
- Go to https://www.crunchyroll.com/
- Waiting for seconds 
- It shows a red banner

**Comment by willingtonortiz** [comment]
Hi my dear customer, here is a list of possible solutions to your problem:

1. Verify that your internet connection is working properly.
2. Clear the cache and cookies of your browser.
3. Restart your device.
4. Uninstall and reinstall the Crunchyroll app.
5. Check for any pending updates for the app or browser.
6. Switch to a different browser or device.
7. Reset your Crunchyroll password.
8. Contact Crunchyroll's customer support for further assistance."

**Comment by JairHuamanBellido** [comment]
Working now!
